Exception on /update [GET]
Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 663, in update
    if config.lastOrderIndex != config.orderInfex and config.lastOrderIndex != 0:
AttributeError: module 'config' has no attribute 'orderInfex'
Exception on /update [GET]
Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 663, in update
    if config.lastOrderIndex != config.orderInfex and config.lastOrderIndex != 0:
AttributeError: module 'config' has no attribute 'orderInfex'
Exception on /update [GET]
Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 663, in update
    if config.lastOrderIndex != config.orderInfex and config.lastOrderIndex != 0:
AttributeError: module 'config' has no attribute 'orderInfex'
Exception on /update [GET]
Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 663, in update
    if config.lastOrderIndex != config.orderInfex and config.lastOrderIndex != 0:
AttributeError: module 'config' has no attribute 'orderInfex'
Exception on /update [GET]
Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 663, in update
    if config.lastOrderIndex != config.orderInfex and config.lastOrderIndex != 0:
AttributeError: module 'config' has no attribute 'orderInfex'
Exception on /update [GET]
Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 663, in update
    if config.lastOrderIndex != config.orderInfex and config.lastOrderIndex != 0:
AttributeError: module 'config' has no attribute 'orderInfex'
Exception on /update [GET]
Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 663, in update
    if config.lastOrderIndex != config.orderInfex and config.lastOrderIndex != 0:
AttributeError: module 'config' has no attribute 'orderInfex'
Exception on /update [GET]
Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 663, in update
    if config.lastOrderIndex != config.orderInfex and config.lastOrderIndex != 0:
AttributeError: module 'config' has no attribute 'orderInfex'
Exception on /update [GET]
Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 663, in update
    if config.lastOrderIndex != config.orderInfex and config.lastOrderIndex != 0:
AttributeError: module 'config' has no attribute 'orderInfex'
Exception on /update [GET]
Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 663, in update
    if config.lastOrderIndex != config.orderInfex and config.lastOrderIndex != 0:
AttributeError: module 'config' has no attribute 'orderInfex'
Exception on /update [GET]
Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 663, in update
    if config.lastOrderIndex != config.orderInfex and config.lastOrderIndex != 0:
AttributeError: module 'config' has no attribute 'orderInfex'
Exception on /update [GET]
Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 663, in update
    if config.lastOrderIndex != config.orderInfex and config.lastOrderIndex != 0:
AttributeError: module 'config' has no attribute 'orderInfex'
Exception on /update [GET]
Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 663, in update
    if config.lastOrderIndex != config.orderInfex and config.lastOrderIndex != 0:
AttributeError: module 'config' has no attribute 'orderInfex'
Exception on /update [GET]
Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 663, in update
    if config.lastOrderIndex != config.orderInfex and config.lastOrderIndex != 0:
AttributeError: module 'config' has no attribute 'orderInfex'
Exception on /update [GET]
Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 663, in update
    if config.lastOrderIndex != config.orderInfex and config.lastOrderIndex != 0:
AttributeError: module 'config' has no attribute 'orderInfex'
Exception on /update [GET]
Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 663, in update
    if config.lastOrderIndex != config.orderInfex and config.lastOrderIndex != 0:
AttributeError: module 'config' has no attribute 'orderInfex'
Exception on /update [GET]
Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 663, in update
    if config.lastOrderIndex != config.orderInfex and config.lastOrderIndex != 0:
AttributeError: module 'config' has no attribute 'orderInfex'
Exception on /update [GET]
Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 663, in update
    if config.lastOrderIndex != config.orderIndex and config.lastOrderIndex != 0:
AttributeError: module 'config' has no attribute 'orderInfex'
Exception on /update [GET]
Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 664, in update
    array_ind = config.order[config.lastOrderIndex].index
TypeError: list indices must be integers or slices, not NoneType
Exception on /update [GET]
Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 664, in update
    array_ind = config.order[config.lastOrderIndex].index
TypeError: list indices must be integers or slices, not NoneType
Exception on /update [GET]
Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 664, in update
    array_ind = config.order[config.lastOrderIndex].index
TypeError: list indices must be integers or slices, not NoneType
Exception on /update [GET]
Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 664, in update
    array_ind = config.order[config.lastOrderIndex].index
TypeError: list indices must be integers or slices, not NoneType
Exception on /update [GET]
Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 664, in update
    array_ind = config.order[config.lastOrderIndex].index
TypeError: list indices must be integers or slices, not NoneType
Exception on /update [GET]
Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 664, in update
    array_ind = config.order[config.lastOrderIndex].index
TypeError: list indices must be integers or slices, not NoneType
Exception on /update [GET]
Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 664, in update
    array_ind = config.order[config.lastOrderIndex].index
TypeError: list indices must be integers or slices, not NoneType
Exception on /update [GET]
Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 664, in update
    array_ind = config.order[config.lastOrderIndex].index
TypeError: list indices must be integers or slices, not NoneType
Exception on /update [GET]
Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 664, in update
    array_ind = config.order[config.lastOrderIndex].index
TypeError: list indices must be integers or slices, not NoneType
Exception on /update [GET]
Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 664, in update
    array_ind = config.order[config.lastOrderIndex].index
TypeError: list indices must be integers or slices, not NoneType
Exception on /update [GET]
Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 664, in update
    array_ind = config.order[config.lastOrderIndex].index
TypeError: list indices must be integers or slices, not NoneType
Exception on /update [GET]
Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 664, in update
    array_ind = config.order[config.lastOrderIndex].index
TypeError: list indices must be integers or slices, not NoneType
Exception on /update [GET]
Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 664, in update
    array_ind = config.order[config.lastOrderIndex].index
TypeError: list indices must be integers or slices, not NoneType
Exception on /update [GET]
Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 664, in update
    array_ind = config.order[config.lastOrderIndex].index
TypeError: list indices must be integers or slices, not NoneType
Exception on /update [GET]
Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 664, in update
    array_ind = config.order[config.lastOrderIndex].index
TypeError: list indices must be integers or slices, not NoneType
Exception on /update [GET]
Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 664, in update
    array_ind = config.order[config.lastOrderIndex].index
TypeError: list indices must be integers or slices, not NoneType
Exception on /update [GET]
Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 664, in update
    array_ind = config.order[config.lastOrderIndex].index
TypeError: list indices must be integers or slices, not NoneType
Exception on /start [POST]
Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 806, in start_generating
    publisher.publish("testni publish")
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 74, in publish
    raise TypeError('Expected {}, got {}'.format(self.msg_type, type(msg)))
TypeError: Expected <class 'std_msgs.msg._string.String'>, got <class 'str'>
Exception on /update [GET]
Traceback (most recent call last):
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 650, in check_arduino_sensor_status
    if time.time() - config.arduino_times[i] > 120 and config.arduino_status[i] != True:
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 766, in update
    check_arduino_sensor_status()
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 655, in check_arduino_sensor_status
    print(e)
UnboundLocalError: local variable 'e' referenced before assignment
Exception on /update [GET]
Traceback (most recent call last):
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 650, in check_arduino_sensor_status
    if time.time() - config.arduino_times[i] > 120 and config.arduino_status[i] != True:
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 766, in update
    check_arduino_sensor_status()
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 655, in check_arduino_sensor_status
    print(e)
UnboundLocalError: local variable 'e' referenced before assignment
Exception on /update [GET]
Traceback (most recent call last):
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 650, in check_arduino_sensor_status
    if time.time() - config.arduino_times[i] > 120 and config.arduino_status[i] != True:
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 766, in update
    check_arduino_sensor_status()
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 655, in check_arduino_sensor_status
    print(e)
UnboundLocalError: local variable 'e' referenced before assignment
Exception on /update [GET]
Traceback (most recent call last):
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 650, in check_arduino_sensor_status
    if time.time() - config.arduino_times[i] > 120 and config.arduino_status[i] != True:
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 766, in update
    check_arduino_sensor_status()
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 655, in check_arduino_sensor_status
    print(e)
UnboundLocalError: local variable 'e' referenced before assignment
Exception on /update [GET]
Traceback (most recent call last):
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 650, in check_arduino_sensor_status
    if time.time() - config.arduino_times[i] > 120 and config.arduino_status[i] != True:
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 766, in update
    check_arduino_sensor_status()
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 655, in check_arduino_sensor_status
    print(e)
UnboundLocalError: local variable 'e' referenced before assignment
Exception on /update [GET]
Traceback (most recent call last):
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 650, in check_arduino_sensor_status
    if time.time() - config.arduino_times[i] > 120 and config.arduino_status[i] != True:
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 766, in update
    check_arduino_sensor_status()
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 655, in check_arduino_sensor_status
    print(e)
UnboundLocalError: local variable 'e' referenced before assignment
Exception on /update [GET]
Traceback (most recent call last):
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 650, in check_arduino_sensor_status
    if time.time() - config.arduino_times[i] > 120 and config.arduino_status[i] != True:
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 766, in update
    check_arduino_sensor_status()
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 655, in check_arduino_sensor_status
    print(e)
UnboundLocalError: local variable 'e' referenced before assignment
Exception on /update [GET]
Traceback (most recent call last):
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 650, in check_arduino_sensor_status
    if time.time() - config.arduino_times[i] > 120 and config.arduino_status[i] != True:
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 766, in update
    check_arduino_sensor_status()
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 655, in check_arduino_sensor_status
    print(e)
UnboundLocalError: local variable 'e' referenced before assignment
Exception on /update [GET]
Traceback (most recent call last):
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 650, in check_arduino_sensor_status
    if time.time() - config.arduino_times[i] > 120 and config.arduino_status[i] != True:
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 766, in update
    check_arduino_sensor_status()
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 655, in check_arduino_sensor_status
    print(e)
UnboundLocalError: local variable 'e' referenced before assignment
Exception on /update [GET]
Traceback (most recent call last):
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 650, in check_arduino_sensor_status
    if time.time() - config.arduino_times[i] > 120 and config.arduino_status[i] != True:
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 766, in update
    check_arduino_sensor_status()
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 655, in check_arduino_sensor_status
    print(e)
UnboundLocalError: local variable 'e' referenced before assignment
Exception on /update [GET]
Traceback (most recent call last):
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 650, in check_arduino_sensor_status
    if time.time() - config.arduino_times[i] > 120 and config.arduino_status[i] != True:
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 766, in update
    check_arduino_sensor_status()
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 655, in check_arduino_sensor_status
    print(e)
UnboundLocalError: local variable 'e' referenced before assignment
Exception on /update [GET]
Traceback (most recent call last):
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 650, in check_arduino_sensor_status
    if time.time() - config.arduino_times[i] > 120 and config.arduino_status[i] != True:
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 766, in update
    check_arduino_sensor_status()
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 655, in check_arduino_sensor_status
    print(e)
UnboundLocalError: local variable 'e' referenced before assignment
Exception on /update [GET]
Traceback (most recent call last):
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 650, in check_arduino_sensor_status
    if time.time() - config.arduino_times[i] > 120 and config.arduino_status[i] != True:
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 766, in update
    check_arduino_sensor_status()
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 655, in check_arduino_sensor_status
    print(e)
UnboundLocalError: local variable 'e' referenced before assignment
Exception on /update [GET]
Traceback (most recent call last):
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 650, in check_arduino_sensor_status
    if time.time() - config.arduino_times[i] > 120 and config.arduino_status[i] != True:
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 766, in update
    check_arduino_sensor_status()
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 655, in check_arduino_sensor_status
    print(e)
UnboundLocalError: local variable 'e' referenced before assignment
Exception on /update [GET]
Traceback (most recent call last):
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 650, in check_arduino_sensor_status
    if time.time() - config.arduino_times[i] > 120 and config.arduino_status[i] != True:
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 766, in update
    check_arduino_sensor_status()
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 655, in check_arduino_sensor_status
    print(e)
UnboundLocalError: local variable 'e' referenced before assignment
Exception on /update [GET]
Traceback (most recent call last):
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 650, in check_arduino_sensor_status
    if time.time() - config.arduino_times[i] > 120 and config.arduino_status[i] != True:
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 766, in update
    check_arduino_sensor_status()
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 655, in check_arduino_sensor_status
    print(e)
UnboundLocalError: local variable 'e' referenced before assignment
Exception on /update [GET]
Traceback (most recent call last):
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 650, in check_arduino_sensor_status
    if time.time() - config.arduino_times[i] > 120 and config.arduino_status[i] != True:
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 766, in update
    check_arduino_sensor_status()
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 655, in check_arduino_sensor_status
    print(e)
UnboundLocalError: local variable 'e' referenced before assignment
Exception on /update [GET]
Traceback (most recent call last):
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 650, in check_arduino_sensor_status
    if time.time() - config.arduino_times[i] > 120 and config.arduino_status[i] != True:
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 766, in update
    check_arduino_sensor_status()
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 655, in check_arduino_sensor_status
    print(e)
UnboundLocalError: local variable 'e' referenced before assignment
Exception on /update [GET]
Traceback (most recent call last):
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 650, in check_arduino_sensor_status
    if time.time() - config.arduino_times[i] > 120 and config.arduino_status[i] != True:
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 766, in update
    check_arduino_sensor_status()
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 655, in check_arduino_sensor_status
    print(e)
UnboundLocalError: local variable 'e' referenced before assignment
Exception on /update [GET]
Traceback (most recent call last):
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 650, in check_arduino_sensor_status
    if time.time() - config.arduino_times[i] > 120 and config.arduino_status[i] != True:
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spider/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 766, in update
    check_arduino_sensor_status()
  File "/home/spider/ros2_ws/src/flask_server/scripts/server.py", line 655, in check_arduino_sensor_status
    print(e)
UnboundLocalError: local variable 'e' referenced before assignment
